import Providers from '@/components/Providers'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default  function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className="min-h-screen bg-gradient-to-br from-slate-50 via-emerald-100 to-teal-300">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
