import SideBar from "@/components/SideBar";
import { authOptions } from "@/lib/auth";
import { getServerSession } from "next-auth";
import { notFound } from "next/navigation";

export const metadata = {
  title: "The chat App",
  description: "Generated by create Moncef Aissaoui",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  
  const session = await getServerSession(authOptions)
  
  
  if(!session) notFound()
  
  return (
    <main className="min-w-full min-h-screen  flex">
      <section className="flex bg-slate-50 min-h-screen w-full max-w-xs grow">   
        <SideBar /> 
    
      </section>
      <main className="p-5  min-h-screen w-full border border-emerald-50 shadow-sm shadow-emerald-100 rounded-xl ">
        <main className="p-2 w-full h-full  bg-slate-50 border border-emerald-50 shadow-sm shadow-emerald-100 rounded-xl ">
          {children}
        </main>
      </main>
    </main>
  );
}
